const UNINTIALIZED = -1;
const BOMB = 9;
const FLAG = 10;
const BLANK = 11;
const MISFLAG = 12;

const HEX_REVEALED = "#90EE90";
const HEX_LIGHT = "#FFB6C1";
const HEX_DARK = "#CBC3E3";

const HEX_REVEALED_HOVERED = "#A0FEA0";
const HEX_LIGHT_HOVERED = "#FFC6D1";
const HEX_DARK_HOVERED = "#DBD3F3";

export {
  UNINTIALIZED,
  BOMB,
  FLAG,
  BLANK,
  MISFLAG,
  HEX_REVEALED,
  HEX_LIGHT,
  HEX_DARK,
  HEX_REVEALED_HOVERED,
  HEX_LIGHT_HOVERED,
  HEX_DARK_HOVERED,
};
