const UNINTIALIZED = -1;
const BOMB = 9;
const FLAG = 10;
const BLANK = 11;

const HEX_REVEALED = "#90EE90";
const HEX_LIGHT = "#FFB6C1";
const HEX_DARK = "#CBC3E3";

const HEX_HOVERED_REVEALED = "#A0FEA0";
const HEX_HOVERED_LIGHT = "#FFC6D1";
const HEX_HOVERED_DARK = "#DBD3F3";

export {
  UNINTIALIZED,
  BOMB,
  FLAG,
  BLANK,
  HEX_REVEALED,
  HEX_LIGHT,
  HEX_DARK,
  HEX_HOVERED_REVEALED,
  HEX_HOVERED_LIGHT,
  HEX_HOVERED_DARK,
};
